import pytest
import requests
from typing import Dict

BASE_URL = "https://api.example.com"


# ─────────────────────────────────────────────
# Auto-generated by QA-09 Postman→Pytest Tool
# E-Commerce API Test Suite
# ─────────────────────────────────────────────


# ─────────────────────────────────────────────
# Fixtures
# ─────────────────────────────────────────────

@pytest.fixture(scope="session")
def auth_headers() -> Dict[str, str]:
    """Authenticate and return headers with token"""
    response = requests.post(
        BASE_URL + "/auth/login",
        json={"email": "user@test.com", "password": "secret123"}
    )
    assert response.status_code == 200, "Login failed"
    token = response.json().get("token", "")
    return {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json"
    }


@pytest.fixture(autouse=True)
def log_test(request):
    """Automatically log test execution"""
    print(f"\n▶ Running: {request.node.name}")
    yield
    print(f"  ✓ Completed: {request.node.name}")


# ─────────────────────────────────────────────
# Authentication Tests
# ─────────────────────────────────────────────

def test_auth_login():
    """Login — POST https://api.example.com/auth/login"""
    payload = {"email": "user@test.com", "password": "secret123"}
    response = requests.post(
        BASE_URL + "/auth/login",
        json=payload,
        headers={"Content-Type": "application/json"}
    )
    
    assert response.status_code == 200, \
        f"Expected 200, got {response.status_code}"
    assert "token" in response.json(), "Response missing 'token' field"


# ─────────────────────────────────────────────
# User Tests
# ─────────────────────────────────────────────

def test_users_get_all_users(auth_headers):
    """Get All Users — GET https://api.example.com/users"""
    response = requests.get(
        BASE_URL + "/users",
        headers=auth_headers
    )
    
    assert response.status_code == 200, \
        f"Expected 200, got {response.status_code}"
    assert isinstance(response.json(), list), "Response must be an array"


def test_users_get_user_by_id(auth_headers):
    """Get User by ID — GET https://api.example.com/users/1"""
    response = requests.get(
        BASE_URL + "/users/1",
        headers=auth_headers
    )
    
    assert response.status_code == 200, \
        f"Expected 200, got {response.status_code}"
    assert "id" in response.json(), "Response missing 'id' field"


def test_users_create_user(auth_headers):
    """Create User — POST https://api.example.com/users"""
    payload = {"name": "John Doe", "email": "john@example.com", "role": "user"}
    response = requests.post(
        BASE_URL + "/users",
        json=payload,
        headers=auth_headers
    )
    
    assert response.status_code == 201, \
        f"Expected 201, got {response.status_code}"
    assert "id" in response.json(), "Response missing 'id' field"


def test_users_update_user(auth_headers):
    """Update User — PUT https://api.example.com/users/1"""
    payload = {"name": "John Updated", "email": "john.updated@example.com"}
    response = requests.put(
        BASE_URL + "/users/1",
        json=payload,
        headers=auth_headers
    )
    
    assert response.status_code == 200, \
        f"Expected 200, got {response.status_code}"


def test_users_delete_user(auth_headers):
    """Delete User — DELETE https://api.example.com/users/1"""
    response = requests.delete(
        BASE_URL + "/users/1",
        headers=auth_headers
    )
    
    assert response.status_code == 204, \
        f"Expected 204, got {response.status_code}"


# ─────────────────────────────────────────────
# Product Tests
# ─────────────────────────────────────────────

def test_products_get_all_products(auth_headers):
    """Get All Products — GET https://api.example.com/products"""
    response = requests.get(
        BASE_URL + "/products",
        headers=auth_headers
    )
    
    assert response.status_code == 200, \
        f"Expected 200, got {response.status_code}"
    assert isinstance(response.json(), list), "Response must be an array"


def test_products_get_product_by_id(auth_headers):
    """Get Product by ID — GET https://api.example.com/products/1"""
    response = requests.get(
        BASE_URL + "/products/1",
        headers=auth_headers
    )
    
    assert response.status_code == 200, \
        f"Expected 200, got {response.status_code}"


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
